"""initial schema

Revision ID: 1eabd5ee9d28
Revises: 
Create Date: 2026-04-02 12:20:29.655608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eabd5ee9d28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('cohort', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('growth_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('drive_url', sa.String(length=500), nullable=True),
    sa.Column('emailed', sa.Boolean(), nullable=True),
    sa.Column('delta_act', sa.Float(), nullable=True),
    sa.Column('delta_cmi', sa.Float(), nullable=True),
    sa.Column('delta_rsem', sa.Float(), nullable=True),
    sa.Column('delta_ewb', sa.Float(), nullable=True),
    sa.Column('cohens_d', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('survey_type', sa.String(length=4), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('sheet_row_index', sa.Integer(), nullable=False),
    sa.Column('act_a1', sa.Float(), nullable=True),
    sa.Column('act_a2', sa.Float(), nullable=True),
    sa.Column('act_a3', sa.Float(), nullable=True),
    sa.Column('act_a4', sa.Float(), nullable=True),
    sa.Column('act_a5', sa.Float(), nullable=True),
    sa.Column('act_a6', sa.Float(), nullable=True),
    sa.Column('act_total', sa.Float(), nullable=True),
    sa.Column('act_connect', sa.Float(), nullable=True),
    sa.Column('act_act', sa.Float(), nullable=True),
    sa.Column('act_thrive', sa.Float(), nullable=True),
    sa.Column('cmi_b1', sa.Float(), nullable=True),
    sa.Column('cmi_b2', sa.Float(), nullable=True),
    sa.Column('cmi_b3', sa.Float(), nullable=True),
    sa.Column('cmi_b4', sa.Float(), nullable=True),
    sa.Column('cmi_b5', sa.Float(), nullable=True),
    sa.Column('cmi_b6', sa.Float(), nullable=True),
    sa.Column('cmi_total', sa.Float(), nullable=True),
    sa.Column('rsem_c1', sa.Float(), nullable=True),
    sa.Column('rsem_c2', sa.Float(), nullable=True),
    sa.Column('rsem_c3', sa.Float(), nullable=True),
    sa.Column('rsem_c4', sa.Float(), nullable=True),
    sa.Column('rsem_c5', sa.Float(), nullable=True),
    sa.Column('rsem_c6', sa.Float(), nullable=True),
    sa.Column('rsem_c7', sa.Float(), nullable=True),
    sa.Column('rsem_c8', sa.Float(), nullable=True),
    sa.Column('rsem_c9', sa.Float(), nullable=True),
    sa.Column('rsem_c10', sa.Float(), nullable=True),
    sa.Column('rsem_total', sa.Float(), nullable=True),
    sa.Column('ewb_d1', sa.Float(), nullable=True),
    sa.Column('ewb_d2', sa.Float(), nullable=True),
    sa.Column('ewb_d3', sa.Float(), nullable=True),
    sa.Column('ewb_d4', sa.Float(), nullable=True),
    sa.Column('ewb_d5', sa.Float(), nullable=True),
    sa.Column('ewb_d6', sa.Float(), nullable=True),
    sa.Column('ewb_total', sa.Float(), nullable=True),
    sa.Column('reflect_e1', sa.Text(), nullable=True),
    sa.Column('reflect_e2', sa.Text(), nullable=True),
    sa.Column('reflect_e3', sa.Text(), nullable=True),
    sa.Column('reflect_e4', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_responses_sheet_row_index'), ['sheet_row_index'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_responses_sheet_row_index'))

    op.drop_table('survey_responses')
    op.drop_table('growth_cards')
    op.drop_table('users')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_code'))

    op.drop_table('participants')
    # ### end Alembic commands ###
